### PR TITLE
add sa namespace configuration

### PR DESCRIPTION
**Pull request by Codenxp**

### CODE REVIEW

**Comment by nmaupu** [comment]
Hi, thanks for submitting this.
Can you update the CRD ?

**Comment by nmaupu** [comment]
🤔 security wise, that seems a bad idea. Any namespace will then be able to read a secret from another namespace just using its name.

**Comment by primeroz** [comment]
I agree it actually breaks the security design for me. 

The reason i chosed this operator vs others was so that i could make sure rbac in namespaces would limit the boundaries of what secrets / sa could be retrieved and so which secrets in vault could be access for each of my teams. 

Unless i don't understand the purpose of this why would you want to go cross-namespace ?

**Comment by Codenxp** [comment]
Yeah, from security's concern, this maybe not a very good idea. 

This update is based on our use case and could be much more convenient for us. Because each of our application has more than one namespaces, if they want to use this operator, they need to prepare a ServiceAccount with clusterrole in each namespace, this will add much more work for application administrators.

With this update, only one serviceaccount in one namespace could satisfy our requirement.

**Comment by primeroz** [comment]
Hi @Codenxp , not sure if you saw my comment in the issue you opened https://github.com/nmaupu/vault-secret/issues/30#issuecomment-832084333 but for us the solution to something similar was to use the `default` serviceaccount in every namespace using a `single role` on the vault side and creating a `VaultSecret` in every namespace

> if they want to use this operator, they need to prepare a ServiceAccount with clusterrole in each namespace

this is not entirely true, the serviceaccount does not need any role binding to it if it is to be used _just_ to pull a secret from vault using the vaultsecret. 

> Because each of our application has more than one namespaces

You will still need to create a `VaultSecret` in each namespace, so why don't you create alongside it a serviceaccount just for this purpose, no need of role binding or anything, with the same name for each namespace and use a single role on vault ?

**Comment by Codenxp** [comment]
Thank you @primeroz , this is a good idea. I will have a test with your suggestion.

**Pull request closed without merging**
